#!/usr/bin/env bash

SINK="$(pactl list short | grep RUNNING | grep -Eo "^[0-9]*")"

if [ -z "$SINK" ]; then SINK=0; fi

pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(($SINK+1)) | tail -n1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
