#!/usr/bin/env bash
# a script to increase volume with a software limit

inc="${1:-0}"

SINK="$(pactl list short | grep RUNNING | grep -Eo "^[0-9]*")"

if [ -z "$SINK" ]; then SINK=0; fi


limit="100"

if [[ "${2:-no}" = "force" ]]; then
	limit="200"
fi


if [[ $inc -lt 0 ]]; then
	pactl set-sink-volume "$SINK" "${inc}%"

elif [[ $(getvol) -lt $limit ]]; then
	pactl set-sink-volume "$SINK" "${inc}%"
fi
