#!/usr/bin/env bash
# a script to increase volume with a software limit

export LC=C 
export LC_ALL=C 

inc="${1:-0}"


limit="100"

if [[ "${2:-no}" = "force" ]]; then
	limit="200"
fi


current=$(amixer get Master | grep Left | grep -Eo "[0-9]*%" | cut -d'%' -f1)


if [[ $inc -lt 0 ]]; then
	amixer set Master "$(($current + $inc))%"

elif [[ $current -lt $limit ]]; then
	amixer set Master "$(($current + $inc))%"

fi
